FROM node:18-alpine
WORKDIR /usr/src/app
COPY web/package.json web/package-lock.json* ./web/
WORKDIR /usr/src/app/web
COPY web/package.json web/package-lock.json ./
RUN npm ci
COPY web/ ./
RUN npm run build

RUN mkdir -p /usr/src/app/shared
VOLUME ["/usr/src/app/shared"]

RUN ln -sf /usr/src/app/shared/graph.json /usr/src/app/web/graph.json

EXPOSE 8080
ENTRYPOINT ["npx", "live-server", "--port=8080", "--no-browser", "/usr/src/app/web"]
